### ISSUE TITLE
Skips to Decoration if the Skill has no Levels

### ISSUE THREAD

**Issue by rayman13579** [Kairuni/Monster-Hunter-World-Armor-Set-Builder#1]
The program seems to skip to the Decoration count after typing a skill with no Level, for example Critical Status or Bludgeoner

**Comment by Kairuni** [comment]
Ah, set bonus skills are currently not included. I didn't actually realize they were a thing at the time, and was very sad to learn that 'Guard Up' is only on the Uragaan bits. :[

Going to close this until I actually add set bonus things, but I suspect I'll have to add them as 'Bludgeoner 1' still to make it play nice with the queries.
